black    = "#162324"
white    = "#EDF2F2"
gray1    = "#B5C9C9"
gray2    = "#839191"
gray3    = "#565959"
gray4    = "#262727"
red      = "#F04341"
green    = "#A4FA87"
yellow   = "#F0E09E"
magenta  = "#F06EE2"
blue     = "#7377FA"
cyan     = "#74E3DA"
